CREATE DATABASE Loja_1
	DEFAULT CHARSET = utf8
    DEFAULT COLLATE = utf8_general_ci;


USE Loja_1;

CREATE TABLE Estado(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL DEFAULT '',
    UF CHAR(2) NOT NULL DEFAULT ''    
);

CREATE TABLE IF NOT EXISTS Municipio(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Estado_ID INT NOT NULL FOREIGN KEY(Estado.ID),
    Nome VARCHAR(80) NOT NULL,
    CodIBGE INT NOT NULL     
);